name: glow_guru
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2


  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  camera: ^0.10.5+6
  image_picker: ^1.0.4
  animated_bottom_navigation_bar: ^1.3.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
